production: &default
  adapter: postgresql
  database: awesomefoundation_production
  pool: 5
  timeout: 5000

development: &default
  adapter: postgresql
  database: <%= ENV['DB_NAME'] || 'awesomefoundation_development' %>
  pool: 5
  timeout: 5000
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  username: <%= ENV['POSTGRES_USER'] || 'root' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || '' %>

test: &test
  <<: *default
  database: awesomefoundation_test
  min_messages: warning

cucumber:
  <<: *test
